### ISSUE TITLE
[Bug] Redundant message history storage

### ISSUE THREAD

**Issue by jeffbryner** [agno-agi/agno#2500]
# Description
When set to use storage to create memories, summaries, etc agno tends to keep redundant copies of chat history leading to bloated storage and inefficient/slow response

## Steps to Reproduce
Create an agent using all the storage features, have a lengthy chat and examine the agent sessions storage database entry. 

## Agent Configuration (if applicable)
I'm using an agent with firestore storage for a nosql experience. I noticed this when firestore complained about the document being over the limit for firestore. 

```
# agno chat agent
chat_agent = Agent(
    telemetry=False,
    monitoring=False,
    user_id="unknown",
    model=model_pro,
    storage=FirestoreStorage(
        collection_name="agent_sessions",
    ),
    # Store memories in Firestore
    memory=AgentMemory(
        db=FirestoreMemoryDb(),
        create_user_memories=True,
        create_session_summary=True,
        update_user_memories_after_run=True,
        update_session_summary_after_run=True,
        classifier=MemoryClassifier(model=model_flash),
        summarizer=MemorySummarizer(model=model_flash),
        manager=MemoryManager(model=model_flash),
    ),
    # Set add_history_to_messages=true to add the previous chat history to the messages sent to the Model.
    add_history_to_messages=True,
    # Number of historical responses to add to the messages.
    num_history_responses=30,
    read_chat_history=True,
    create_default_user_message=False,
    retries=3,
    instructions=chat_agent_instructions,
    additional_context=more_stuff,
    markdown=True,
)
```

## Expected Behavior
I would expect agno to store a single copy of the messages in the chat and reference it when referring to the history. 

## Actual Behavior
Agno appears to store: 
- memory.messages that holds a current  record of the conversation
<img width="326" alt="Image" src="https://github.com/user-attachments/assets/dddacb93-1cd0-42f9-9512-aaec181f736f" />

- memory.runs.response.messages that also holds a record of the conversation for each run of the agent

<img width="536" alt="Image" src="https://github.com/user-attachments/assets/d2aa90d7-43dc-4f3b-ba24-4d1ef356f375" />

When adding past conversation to the chat history; agno appears to use the latter and relies on the "from_history" field to weed out every copy of messages in all the runs to produce the same thing that the memory.messages list already holds.
https://github.com/agno-agi/agno/blob/main/libs/agno/agno/memory/agent.py#L134

## Possible Solutions (optional)
I would think that: 
- memory.runs would not store message history
- references to the chat history would only use the existing memory.messages list

## Additional Context
This is particularly expensive when there are lengthy system instructions involved which are stored multiple times for each time the agent is run even though they aren't referenced.

**Comment by jeffbryner** [comment]
Also a little confusing that the num_history_responses parameter appears to mean how many messages you'd like to add to the chat history, but it actually controls how many 'runs' are considered. The number of runs doesn't impact the number of messages added to the history, since the entire history is added for the last run. 
https://github.com/agno-agi/agno/blob/main/libs/agno/agno/memory/agent.py#L140

It would appear that this function should actually be used: https://github.com/agno-agi/agno/blob/main/libs/agno/agno/memory/agent.py#L130
And could return the selected history responses by reverse sorting the list it derives? https://github.com/agno-agi/agno/blob/main/libs/agno/agno/memory/agent.py#L132

**Comment by ysolanky** [comment]
Hello @jeffbryner! I am happy to answer any questions. 

In `session["memory"]`, all messages from every run of the session are stored. Meanwhile, `session["memory"]["response"]["runs"]` specifically contains the messages that were sent to the model to generate a particular response. In your case, both are identical because you have set `num_history_responses=30`, meaning the messages from past 30 runs are always included in the model's context.

>Also a little confusing that the num_history_responses parameter appears to mean how many messages you'd like to add to the chat history, but it actually controls how many 'runs' are considered. The number of runs doesn't impact the number of messages added to the history, since the entire history is added for the last run.

Yes, this is correct. The `num_history_responses` parameter controls how many past "runs" contribute messages to the current request. However, the naming isn't very intuitive and should be updated in the next major release.

The reasoning behind this implementation is that most major model providers expect message history to be structured in pairs. For instance, if we were to limit history by the number of individual messages rather than runs, we might include only the tool call result but not the corresponding tool call itself, causing the API to throw an error. By filtering based on runs instead of messages, we ensure that all messages within a run are grouped together, preserving context and preventing errors.

Please let me know if you have any questions. I really appreciate the deep dive and the time you spent on this

**Comment by jeffbryner** [comment]
Hi @ysolanky , appreciate the response. 
I understand the need to show a complete conversation to the model and appreciate the call out of tool responses as an example. Seems like we could do this by just using the last run? 

If I understand the code correctly; no matter now many runs you ask to be included only the last one is actually considered due to filtering on the 'from history' attribute? 
https://github.com/agno-agi/agno/blob/main/libs/agno/agno/memory/agent.py#L161

In my case I'm more worried about session storage bloat since each run holds a copy of the previous run's messages in addition to the messages being stored in session["memory"]. I've also noticed the messages appear to also be stored in agent_run.response.extra_data for each run?

If it's helpful I mocked up a class that uses less storage and seems to work. I haven't paid much attention to tool calls, but it certainly reduces the session object size, reduces parsing and network overhead: 

```
class LightAgentMemory(AgentMemory):
    """
    A subclass of AgentMemory that only keeps the most recent run
    instead of maintaining a history of all runs to prevent exponential bloat of storing messages.
    """

    def add_run(self, agent_run: AgentRun) -> None:
        """
        Overrides the add_run method to only store the latest run
        instead of appending to the runs list.
        """
        # Save as little as possible to not duplicate messages.
        agent_run.response.extra_data = None
        agent_run.response.messages = None
        agent_run.response.metrics = None
        self.runs = [agent_run]
        logger.debug("Replaced previous run with latest AgentRun in LatestRunMemory")

    def get_messages_from_last_n_runs(
        self, last_n: Optional[int] = None, skip_role: Optional[str] = None
    ) -> List[Message]:
        """Ignore the options and returns the messages list instead of traversing the 'runs'"""
        logger.info(
            f"LIGHT AGENT MEMORY: get_messages_from_last_n_runs has {len(self.messages)} messages"
        )

        return [message for message in self.messages]
```
Thanks for having a look!

**Comment by ysolanky** [comment]
> Seems like we could do this by just using the last run?

We can do this if we were to simply add all past messages to the current message as history. This could work in some cases and could be something we can support in the future. The downside would be messages that cost a lot of tokens in a session with a lot of messages. 20+ for example. 

> If I understand the code correctly; no matter now many runs you ask to be included only the last one is actually considered due to filtering on the 'from history' attribute?

No, we still loop through the number of runs defined in the `num_history_responses`. The `from_history` attribute makes sure we only copy the messages from that run, not the messages that were added as history to that run, which would result in an exponential increase.

> each run holds a copy of the previous run's messages in addition to the messages being stored in session["memory"]

Each run only hold the list of messages that were sent to the model to generate that response. While session["memory"] hold all messages across the session. For example, If `num_history_responses` was set to 2, each of your individual run would include all messages from past 2 runs whereas `session["memory"]` would include all messages.

> I've also noticed the messages appear to also be stored in agent_run.response.extra_data for each run?

Yes, the `response.extra_data.history` only contains the messages that were picked up from history while `response.messages` includes both the historical messages and messages from this particular run. I do agree that we can get rid of the former.

Thank for your all the suggestions and questions. I have a PR out with some of the suggested improvements. Please let me know if you have any questions

**Comment by jeffbryner** [comment]
I'm not sure I understand how the 'from_history' attribute is being used? 

I ran some code over a session with 3 user messages and 3 runs. 

```
for a_run in session['memory']['runs']:
    print('----run ----')
    for r in a_run['response']['messages']:
        print(f"role: {r['role']:>10}         from_history: {r['from_history']:>10}")
    if 'extra_data' in a_run['response']:
        print("----extra data history----")
        for r in a_run['response']['extra_data']['history']:
            print(f"role: {r['role']:>10}         from_history: {r['from_history']:>10}")
```

This is how the storage worked out
```
----run ----
role:     system         from_history:          0
role:       user         from_history:          0
role:  assistant         from_history:          0
----run ----
role:     system         from_history:          0
role:       user         from_history:          1
role:  assistant         from_history:          1
role:       user         from_history:          0
role:  assistant         from_history:          0
----extra data history----
role:       user         from_history:          1
role:  assistant         from_history:          1
----run ----
role:     system         from_history:          0
role:       user         from_history:          1
role:  assistant         from_history:          1
role:       user         from_history:          1
role:  assistant         from_history:          1
role:       user         from_history:          0
role:  assistant         from_history:          0
----extra data history----
role:       user         from_history:          1
role:  assistant         from_history:          1
role:       user         from_history:          1
role:  assistant         from_history:          1
```

If I understand correctly this would mean the system message is included from each run since from_history is zero/false?
https://github.com/agno-agi/agno/blob/main/libs/agno/agno/memory/agent.py#L160

**Comment by jeffbryner** [comment]
Thanks! I turned debug_mode=True and continued the conversation above. Here's what it said: 
```
DEBUG    -*- AgentSession loaded: <sessionid>
DEBUG    Memories loaded for user: <userid>                                                               
INFO     AGENT MEMORY: runs to process 3                                                                                                   
DEBUG    Getting messages from previous runs: 6                                                                                            
INFO     AGENT MEMORY: get_messages_from_last_n_runs has 6 messages                                                                        
DEBUG    Adding 6 messages from history
```
Thanks for helping me understand. So it picks the last messages from each run and uses that to seed the conversation rather than using the conversation from the last run (which appears to have the same messages)?

**Comment by ysolanky** [comment]
@jeffbryner of course. Happy to help! I have merged the PR to remove history from `extra_data`. So thank you for your deep dive once again.

> So it picks the last messages from each run and uses that to seed the conversation rather than using the conversation from the last run (which appears to have the same messages)?

Essentially, yes. The goal is to provide only the input-output pair from the last run as input to the current run, without including the previous run’s history. This prevents unnecessary duplication and keeps the history concise.

**Comment by jeffbryner** [comment]
> Essentially, yes. The goal is to provide only the input-output pair from the last run as input to the current run, without including the previous run’s history. This prevents unnecessary duplication and keeps the history concise.

Thanks! I'm still missing something; 
- all the history is in the last run
- all the history up to the last run is also in the previous runs (i.e. run 0 has 2 messages, run 1 has 4, run 2 has 6 etc)

So history is duplicated each time another run happens? But to get history (which is in the latest run), the previous runs are traversed to get history? 
It seems this strategy is duplicating history (especially length system instructions) and potentially creating a performance impact as each run is traversed to get what is already in the last run? 

I believe I notice it when agno with all the nifty memory/session features is used in a lengthy conversation with a large system instruction. The longer the conversation goes on, the slower the interaction gets especially with a wordy model. 

If it's just me I can subclass the memory object and create custom behavior, just wanted to raise it because performance seems core to agno (which I love!).
