### ISSUE TITLE
[Bug] UnboundLocalError: cannot access local variable 'result' in arun_function_call during streaming response

### ISSUE THREAD

**Issue by JasonLovesDoggo** [agno-agi/agno#5071]
### Description

When using agno 2.1.5, a streaming response occasionally crashes due to an UnboundLocalError in arun_function_call.
It appears that result is referenced before assignment when an exception is raised during a function call execution.

### Steps to Reproduce

1. Run an async agent with streaming responses enabled
2. Trigger any model function call inside a streaming session.
3. Observe the traceback in some cases

### Agent Configuration (if applicable)

Let me know if wanted. dont think it's needed

### Expected Behavior

The function call should handle errors gracefully and propagate exceptions without referencing undefined locals.

### Actual Behavior

UnboundLocalError: cannot access local variable 'result' where it is not associated with a value

Full traceback

```py
  File "stanley/api/chat.py", line 242, in generate_response
    async for chunk in await agent.get_streaming_response(
  File "agno/agent/agent.py", line 1818, in _arun_stream
    async for event in self._ahandle_model_response_stream(
  File "agno/agent/agent.py", line 3973, in _ahandle_model_response_stream
    async for model_response_event in model_response_stream:  # type: ignore
  File "agno/models/base.py", line 939, in aresponse_stream
    async for function_call_response in self.arun_function_calls(
  File "agno/models/base.py", line 1680, in arun_function_calls
    raise original_result
  File "agno/models/base.py", line 1446, in arun_function_call
    return success, function_call_timer, function_call, result
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value

```

### Environment

```markdown
agno version: 2.1.5

Python: 3.13.8
```

### Possible Solutions (optional)

Initialize result = None before the try block in arun_function_call to ensure it exists even if an exception interrupts assignment.

**Comment by ron-42** [comment]
@JasonLovesDoggo I think this issue is fixed in the v 2.1.7, i tried to reproduced this issue as you given the steps but each time it's working fine, i ran this code from cookbook `cookbook/agents/async/streaming.py`.

**Comment by JasonLovesDoggo** [comment]
> [@JasonLovesDoggo](https://github.com/JasonLovesDoggo) I think this issue is fixed in the v 2.1.7, i tried to reproduced this issue as you given the steps but each time it's working fine, i ran this code from cookbook `cookbook/agents/async/streaming.py`.

2.1.6 nor 2.1.7 changes any of this code

Looking at the source it definitely still exists. My steps to reproduce may have been wrong as it's invariant in prod. 

If you look at the source, if a tool raises an exception, result is not defined. https://github.com/JasonLovesDoggo/agno/blob/5e40a2d10b974588efc2f60f08fef0bb18b6181d/libs/agno/agno/models/base.py#L1421-L1437

**Comment by jesalg** [comment]
+1 I'm running into this as well

**Comment by Mustafa-Esoofally** [comment]
Hey @jesalg ! This should be fixed v2.2.2 onwards!
