### ISSUE TITLE
[Bug] Custom events are not fully supported

### ISSUE THREAD

**Issue by hudyweas** [agno-agi/agno#5118]
### Description

Custom events are not fully supported either in the base app or in the AG-UI interface.
Docs show that it should handle custom properties, but features are not supported.

In the current state, the content keyword can only be set for the event to work properly. In the ag-ui interface, only this value is extracted.

### Steps to Reproduce

1. Make custom event
2. Yield it

### Expected Behavior

AG-UI should stream all properties; there should be no warning about unexpected keywords

### Actual Behavior

Streaming no custom properties, there are warnings.

### Environment

```markdown
- macos
- Agno 2.1.8
```

### Additional Context

Logs
```
Exception upserting into table: CustomEvent.__init__() got an unexpected keyword argument 'abc'
Error upserting session into db: CustomEvent.__init__() got an unexpected keyword argument 'abc'
```

AG-UI streamed event
```
data: {"type":"CUSTOM","name":"CustomEvent"}
```

```python
@dataclass
class StateUpdateEvent(CustomEvent):
    abc: Any = None
```

**Comment by 404notfoundyc-L** [comment]
<img width="1213" height="686" alt="Image" src="https://github.com/user-attachments/assets/1ea68177-124a-479e-9dfd-eeb934348799" />

It looks like the source code logic is wrong.


if isinstance(item, RunContentEvent) or isinstance(item, TeamRunContentEvent):   False

         if isinstance(item, CustomEvent): True  # This code should be outside the if condition

**Comment by dirkbrnd** [comment]
@hudyweas 
We just released a fix with `agno` [2.2.1](https://github.com/agno-agi/agno/releases/tag/v2.2.1)

Please let me know if that addresses your issue?

**Comment by hudyweas** [comment]
@dirkbrnd issue is not resolved. We do not have an error, but AG-UI streams this: 

{"type":"CUSTOM","name":"CustomEvent"}

In the current state, custom events are completely useless. We do not have a proper name, nor any attributes from the event.

**Comment by hudyweas** [comment]
My proposal:
- Add new property event_name that will be used in the router as a name instead of chunk.event or use self.__class__.__name__

```python
    elif chunk.event == RunEvent.custom_event:
        custom_event = CustomEvent(name=chunk.event, value=chunk.content)
        events_to_emit.append(custom_event)
```

- create a dict of the values, something that end with a similar result as this:
```python
@dataclass
class ChangeProjectNameEvent(CustomEvent):
    project_name: str = ""

    def __post_init__(self):
        self.content = {"project_name": self.project_name}
```

so we end with an event:

{"type":"CUSTOM","name":"ChangeProjectNameEvent", "value": {"project_name": "some_name"} }

**Comment by hudyweas** [comment]
@dirkbrnd please reopen this issue

**Comment by dirkbrnd** [comment]
@hudyweas We'll take a look

**Comment by manuhortet** [comment]
Hey @hudyweas 

We updated the AG-UI integration. Now when streaming custom events:
- The `name` field will be the class name (as you proposed)
- The `value` field will contain all fields in the used event class. This way streaming all information doesn't depend on the user setting up the correct `__post_init__` logic.

We will release this later today with `v2.2.9` - please let us know if this setup works for you, or if we can help you further.

Thanks for using Agno!

**Comment by dirkbrnd** [comment]
This was released!
